apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: nodeapp
        ports:
        - containerPort: 8080
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          configMap:
            name: nodeapp