apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianini/nodeapp
  newTag: 53ffa66d218b13b0f753912b372db66313ccf3fc
