apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml
- configmap.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianini/nodeapp
  newTag: 394539a244777ea1c69e3cbd179539d929692423
