apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml
- configmap.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianini/nodeapp
  newTag: 30d798de9b8f977eeccef53fcb99321634b62742
